# Generated by Django 5.0 on 2023-12-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='slug_collection',
        ),
    ]
